version: "3.3"

services:
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: cdf_fitness
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    networks:
      - mynet

  myphp:
    depends_on:
      - mysql
    image: cdelaflor29/customphp:8.2-fpm-new
    restart: always
    ports:
      - 9000
    links:
      - 'mysql:mysql'
    volumes:
      - ./src:/var/www/html
    networks:
      - mynet

  mynginx:
    depends_on:
      - myphp
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    links:
      - 'myphp:myphp'
    volumes:
      - ./src:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
    networks:
      - mynet
    deploy:
      replicas: 2

  phpMyAdmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: cdfFitness_mysql
    ports:
      - "8082:80"
    networks:
      - mynet

volumes:
  database: {}

networks:
  mynet:
